### ISSUE TITLE
modify_field action does not work with registers

### ISSUE THREAD

**Issue by Mahdth** [p4lang/p4c-behavioral#8]
modify_field action only work with type field and integer value but not with register.

how can I write a value to register or copy the register value to header field in this case?

**Comment by antoninbas** [comment]
For implementation reasons, we chose not to support registers with the modify_field action primitive (yet). However, you can use register_read and register_write to copy a register to / from a field. Please look them up in the list of supported primitives: https://github.com/p4lang/p4-hlir/blob/master/p4_hlir/frontend/primitives.json

**Comment by Mahdth** [comment]
Thank you
