### ISSUE TITLE
Table without match fields

### ISSUE THREAD

**Issue by czivar** [p4lang/p4c-behavioral#9]
The specification says that the only mandatory field for a table definition is the actions field. However, if the the reads part is is not included (like in the table specification below), the generated cli will not be able to list it or perform any action on it (e.g. set_default_action), as the Thrift template ignores these tables.

An example table:

```
table forward {
    actions {
        _drop;
    }
}
```

If this is a bug, I have a solution to fix this by altering the p4_pd_rpc.thrift template to create an empty struct like below for the tables without match fields. This would then generate a client that can list and work with these tables.

```
struct gossip4_forward_match_spec_t {
}
```

**Comment by antoninbas** [comment]
Richard,

This is indeed a bug and we would be happy to include your contribution. Please submit a pull request with your patch. Note that p4.org now requires contributors to sign a standard Apache CLA before contributing code. I will have someone reach out to you about this and I will need the CLA before I can merge your pull request into the master branch. Thanks.

**Comment by czivar** [comment]
Hi Antonin, will do, thanks!
